### ISSUE TITLE
[Bug] Provide a short description of the bug here

### ISSUE THREAD

**Issue by barto95100** [LePresidente/docker-nginx-proxy-manager#3]
### Current Behavior

not possible to access redirection host menu
Access to redirection host: 
Cannot read properties of null (reading 'avatar')

### Steps To Reproduce

Just connect and select redirectino host and hte result is : 
![CleanShot 2023-12-29 at 14 06 03](https://github.com/LePresidente/docker-nginx-proxy-manager/assets/17863254/72d32dec-5fe3-477f-88b2-6fd194593c1c)

I search on internet and I viex this issue of npm : 
https://github.com/NginxProxyManager/nginx-proxy-manager/issues/230#issuecomment-815078355

but when i test to connect on db and the the command send to resolve my problem, the result is : 
```
MariaDB [npm]> UPDATE user SET is_deleted=1;
ERROR 1146 (42S02): Table 'npm.user' doesn't exist
```

### Environment

- OS: Debian
- OS version: 11 
- Docker version: 20.10.21
- Browser/OS: all browser

### Container creation

```
version: "3"
services:
  npm_lepresident:
    image: 'lepresidente/nginx-proxy-manager:latest'
    restart: always
    container_name: npm-secure-lepresident
    ports:

      - "80:8080"
      - "443:4443"
    environment:
      # This is the default cert used to validate reCAPTCHA
      TZ: "Europe/Paris"
      ADMIN_PANEL_LOG: "1"
      CROWDSEC_BOUNCER: "1"
      OPENRESTY_DEBUG: "0"
      MODSEC_ENABLE: "0"
      CROWDSEC_LAPI: "http://5.x.x.5:8080"
      CROWDSEC_KEY: "64d9176xxxxxxxxxxxxxxxxxxx857be662"

      # These are the settings to access your db
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "xxxxxxxx"
      DB_MYSQL_NAME: "npm"
      # If you would rather use Sqlite uncomment this
      # and remove all DB_MYSQL_* lines above
      # DB_SQLITE_FILE: "/data/database.sqlite"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - /docker/nginx-proxy-manager-president:/config:rw"
      - /docker/nginx-proxy-manager-president/letsencrypt:/etc/letsencrypt
    depends_on:
      - db-lepresident
    networks:
      - default
      - traefik-net
  db-lepresident:
    image: 'jc21/mariadb-aria:latest'
    restart: always
    container_name: npm_db_lepresident
    environment:
      MYSQL_ROOT_PASSWORD: 'xxxxxxxx'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: "xxxxxxxx"
    volumes:
      - /docker/nginx-proxy-manager-president/data/mysql:/var/lib/mysql
    networks:
      - default
networks:
  traefik-net:
    external: true

```

### Container log

```text
[12/28/2023] [4:44:49 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/28/2023] [4:46:29 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/28/2023] [4:46:41 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/28/2023] [4:46:50 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/28/2023] [4:47:10 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/28/2023] [4:47:23 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/28/2023] [4:47:32 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/28/2023] [4:48:01 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/28/2023] [4:48:16 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/28/2023] [4:50:24 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/28/2023] [4:53:02 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/28/2023] [4:53:21 PM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[12/28/2023] [4:53:44 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/28/2023] [4:55:28 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/28/2023] [4:56:11 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/28/2023] [4:56:11 PM] [SSL      ] › ℹ  info      Renew Complete
[12/28/2023] [5:53:21 PM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[12/28/2023] [5:53:24 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/28/2023] [5:53:24 PM] [SSL      ] › ℹ  info      Renew Complete
[12/28/2023] [6:53:21 PM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[12/28/2023] [6:53:21 PM] [IP Ranges] › ℹ  info      Fetching IP Ranges from online services...
[12/28/2023] [6:53:21 PM] [IP Ranges] › ℹ  info      Fetching https://ip-ranges.amazonaws.com/ip-ranges.json
[12/28/2023] [6:53:21 PM] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v4
[12/28/2023] [6:53:21 PM] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v6
[12/28/2023] [6:53:22 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/28/2023] [6:53:24 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/28/2023] [6:53:24 PM] [SSL      ] › ℹ  info      Renew Complete
[12/28/2023] [7:53:21 PM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[12/28/2023] [7:53:24 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/28/2023] [7:53:24 PM] [SSL      ] › ℹ  info      Renew Complete
[12/28/2023] [8:53:21 PM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[12/28/2023] [8:53:24 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/28/2023] [8:53:24 PM] [SSL      ] › ℹ  info      Renew Complete
[12/28/2023] [9:53:21 PM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[12/28/2023] [9:53:24 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/28/2023] [9:53:24 PM] [SSL      ] › ℹ  info      Renew Complete
[12/28/2023] [10:53:21 PM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[12/28/2023] [10:53:24 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/28/2023] [10:53:24 PM] [SSL      ] › ℹ  info      Renew Complete
[12/28/2023] [11:53:21 PM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[12/28/2023] [11:53:24 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/28/2023] [11:53:24 PM] [SSL      ] › ℹ  info      Renew Complete
[12/29/2023] [12:53:18 AM] [Setup    ] › ℹ  info      Logrotate completed.
[12/29/2023] [12:53:21 AM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[12/29/2023] [12:53:21 AM] [IP Ranges] › ℹ  info      Fetching IP Ranges from online services...
[12/29/2023] [12:53:21 AM] [IP Ranges] › ℹ  info      Fetching https://ip-ranges.amazonaws.com/ip-ranges.json
[12/29/2023] [12:53:21 AM] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v4
[12/29/2023] [12:53:21 AM] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v6
[12/29/2023] [12:53:22 AM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/29/2023] [12:53:24 AM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/29/2023] [12:53:24 AM] [SSL      ] › ℹ  info      Renew Complete
[12/29/2023] [1:53:21 AM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[12/29/2023] [1:53:24 AM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/29/2023] [1:53:24 AM] [SSL      ] › ℹ  info      Renew Complete
[12/29/2023] [2:53:21 AM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[12/29/2023] [2:53:24 AM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/29/2023] [2:53:25 AM] [SSL      ] › ℹ  info      Renew Complete
[12/29/2023] [3:53:21 AM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[12/29/2023] [3:53:24 AM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/29/2023] [3:53:24 AM] [SSL      ] › ℹ  info      Renew Complete
[12/29/2023] [4:53:21 AM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[12/29/2023] [4:53:24 AM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/29/2023] [4:53:24 AM] [SSL      ] › ℹ  info      Renew Complete
[12/29/2023] [5:53:21 AM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[12/29/2023] [5:53:24 AM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/29/2023] [5:53:24 AM] [SSL      ] › ℹ  info      Renew Complete
[12/29/2023] [6:53:21 AM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[12/29/2023] [6:53:21 AM] [IP Ranges] › ℹ  info      Fetching IP Ranges from online services...
[12/29/2023] [6:53:21 AM] [IP Ranges] › ℹ  info      Fetching https://ip-ranges.amazonaws.com/ip-ranges.json
[12/29/2023] [6:53:21 AM] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v4
[12/29/2023] [6:53:21 AM] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v6
[12/29/2023] [6:53:22 AM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/29/2023] [6:53:24 AM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/29/2023] [6:53:24 AM] [SSL      ] › ℹ  info      Renew Complete
[12/29/2023] [7:53:21 AM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[12/29/2023] [7:53:24 AM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/29/2023] [7:53:24 AM] [SSL      ] › ℹ  info      Renew Complete
[12/29/2023] [8:53:21 AM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[12/29/2023] [8:53:24 AM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/29/2023] [8:53:24 AM] [SSL      ] › ℹ  info      Renew Complete
[12/29/2023] [9:53:21 AM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[12/29/2023] [9:53:24 AM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/29/2023] [9:53:24 AM] [SSL      ] › ℹ  info      Renew Complete
[12/29/2023] [10:53:21 AM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[12/29/2023] [10:53:24 AM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/29/2023] [10:53:24 AM] [SSL      ] › ℹ  info      Renew Complete
[12/29/2023] [11:53:21 AM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[12/29/2023] [11:53:24 AM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/29/2023] [11:53:24 AM] [SSL      ] › ℹ  info      Renew Complete
[12/29/2023] [12:53:21 PM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[12/29/2023] [12:53:21 PM] [IP Ranges] › ℹ  info      Fetching IP Ranges from online services...
[12/29/2023] [12:53:21 PM] [IP Ranges] › ℹ  info      Fetching https://ip-ranges.amazonaws.com/ip-ranges.json
[12/29/2023] [12:53:21 PM] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v4
[12/29/2023] [12:53:21 PM] [IP Ranges] › ℹ  info      Fetching https://www.cloudflare.com/ips-v6
[12/29/2023] [12:53:22 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/29/2023] [12:53:24 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/29/2023] [12:53:24 PM] [SSL      ] › ℹ  info      Renew Complete
[12/29/2023] [1:53:21 PM] [SSL      ] › ℹ  info      Renewing SSL certs close to expiry...
[12/29/2023] [1:53:24 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[12/29/2023] [1:53:24 PM] [SSL      ] › ℹ  info      Renew Complete
```
